import { User, CandidateProfile, Company, Vacancy, Application, Notification, AnalyticsSummary } from '@/types/models';

const buildAvatarUrl = (name: string, background: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${background}&color=FFFFFF&bold=true&format=png&size=256`;

const buildCompanyLogoUrl = (name: string, background: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${background}&color=FFFFFF&bold=true&format=png&size=256`;

const mockAvatarUrls = {
  aliHasanov:
    'https://www.corporatephotographylondon.com/wp-content/uploads/2019/11/HKstrategies-1210-1024x683.jpg',
  leylaMammadova:
    'https://thumbs.dreamstime.com/b/profile-picture-caucasian-male-employee-posing-office-happy-young-worker-look-camera-workplace-headshot-portrait-smiling-190186649.jpg',
  nigarAliyeva:
    'https://thumbs.dreamstime.com/b/profile-picture-smiling-male-employee-posing-workplace-close-up-headshot-portrait-smiling-caucasian-businessman-look-190961990.jpg',
  raminQuliyev:
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqIZXTe5iRAKg6-DVQypvrm1wuVQtUxsAX1Q&s',
  aytenMuradova:
    'https://images.template.net/547749/Employee-Profile-Picture-Template-edit-online.webp',
} as const;

const mockCompanyLogoUrls = {
  kapitalBank:
    'https://habrastorage.org/getpro/moikrug/uploads/company/100/007/831/1/logo/medium_4cbbb4549ce92e5c6b3b9b341ccb85cb.png',
  azercell:
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsztcc-hBegyyoYfswjrrycf1WNOImwQCR9A&s',
  pashaHolding:
    'https://pasha-holding.az/site/templates/images/share.png',
  abb:
    'https://igrtzfvphltnoiwedbtz.supabase.co/storage/v1/object/public/images/companies/1755687147529-lq1vnwq1ymh.svg',
  bravoSupermarket:
    'https://upload.wikimedia.org/wikipedia/commons/d/d7/Bravo_Supermarketl%C9%99r_%C5%9E%C9%99b%C9%99k%C9%99si.jpg',
} as const;

export const mockUser: User = {
  id: '1',
  email: 'ali@example.com',
  role: 'candidate',
  fullName: 'Əli Həsənov',
  phone: '+994501234567',
  avatarUrl: mockAvatarUrls.aliHasanov || buildAvatarUrl('Əli Həsənov', '1B2E5A'),
  emailVerified: true,
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-03-10T10:00:00Z',
};

export const mockEmployerUser: User = {
  id: '2',
  email: 'hr@azercell.com',
  role: 'employer',
  fullName: 'Leyla Məmmədova',
  phone: '+994502345678',
  avatarUrl: mockAvatarUrls.leylaMammadova || buildAvatarUrl('Leyla Məmmədova', '3755A0'),
  emailVerified: true,
  createdAt: '2024-01-10T10:00:00Z',
  updatedAt: '2024-03-10T10:00:00Z',
};

export const mockCandidateProfile: CandidateProfile = {
  id: '1',
  userId: '1',
  title: 'Senior Frontend Developer',
  location: 'Bakı',
  expectedSalary: 3000,
  salaryCurrency: 'AZN',
  skills: ['React', 'TypeScript', 'Node.js', 'React Native', 'GraphQL', 'PostgreSQL'],
  workExperience: [
    {
      id: '1',
      jobTitle: 'Senior Frontend Developer',
      company: 'Kapital Bank',
      location: 'Bakı',
      startDate: '2022-06-01',
      isCurrent: true,
      description: 'Led the development of the mobile banking application using React Native.',
      highlights: ['Increased app performance by 40%', 'Led team of 5 developers'],
    },
    {
      id: '2',
      jobTitle: 'Frontend Developer',
      company: 'Pasha Holding',
      location: 'Bakı',
      startDate: '2020-03-01',
      endDate: '2022-05-31',
      isCurrent: false,
      description: 'Developed internal corporate tools and customer-facing web applications.',
    },
  ],
  education: [
    {
      id: '1',
      degree: 'Bakalavr',
      fieldOfStudy: 'Kompüter Elmləri',
      institution: 'Bakı Dövlət Universiteti',
      startDate: '2016-09-01',
      endDate: '2020-06-30',
      isCurrent: false,
    },
  ],
  languages: [
    { id: '1', language: 'Azərbaycan dili', level: 'native' },
    { id: '2', language: 'English', level: 'advanced' },
    { id: '3', language: 'Русский', level: 'intermediate' },
  ],
  certifications: [
    {
      id: '1',
      name: 'AWS Solutions Architect',
      issuer: 'Amazon Web Services',
      issueDate: '2023-06-01',
    },
  ],
  portfolioUrl: 'https://alihasanov.dev',
  availability: 'two_weeks',
  workPreference: 'hybrid',
  profileCompleteness: 85,
  bio: 'Passionate software engineer with 4+ years of experience building modern web and mobile applications.',
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-03-10T10:00:00Z',
};

const mockApplicantUsers: User[] = [
  {
    id: '11',
    email: 'nigar.aliyeva@example.com',
    role: 'candidate',
    fullName: 'Nigar Əliyeva',
    phone: '+994551112233',
    avatarUrl: mockAvatarUrls.nigarAliyeva || buildAvatarUrl('Nigar Əliyeva', '0F766E'),
    emailVerified: true,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
  },
  {
    id: '12',
    email: 'ramin.guliyev@example.com',
    role: 'candidate',
    fullName: 'Ramin Quliyev',
    phone: '+994555556677',
    avatarUrl: mockAvatarUrls.raminQuliyev || buildAvatarUrl('Ramin Quliyev', '7C3AED'),
    emailVerified: true,
    createdAt: '2024-02-03T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
  },
  {
    id: '13',
    email: 'ayten.muradova@example.com',
    role: 'candidate',
    fullName: 'Aytən Muradova',
    phone: '+994557778899',
    avatarUrl: mockAvatarUrls.aytenMuradova || buildAvatarUrl('Aytən Muradova', 'C2410C'),
    emailVerified: true,
    createdAt: '2024-02-05T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
  },
];

const mockApplicantProfiles: Array<CandidateProfile & { user: User }> = [
  {
    id: '11',
    userId: '11',
    title: 'Senior DevOps Engineer',
    location: 'Bakı',
    expectedSalary: 4200,
    salaryCurrency: 'AZN',
    skills: ['AWS', 'Terraform', 'Kubernetes', 'CI/CD', 'Linux'],
    workExperience: [],
    education: [],
    languages: [],
    certifications: [],
    availability: 'two_weeks',
    workPreference: 'remote',
    profileCompleteness: 92,
    bio: 'Cloud and infrastructure engineer focused on scalable deployment pipelines.',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
    user: mockApplicantUsers[0],
  },
  {
    id: '12',
    userId: '12',
    title: 'Backend Engineer',
    location: 'Sumqayıt',
    expectedSalary: 3300,
    salaryCurrency: 'AZN',
    skills: ['Node.js', 'PostgreSQL', 'GraphQL', 'Docker', 'Redis'],
    workExperience: [],
    education: [],
    languages: [],
    certifications: [],
    availability: 'one_month',
    workPreference: 'hybrid',
    profileCompleteness: 88,
    bio: 'Backend engineer building resilient APIs and data-heavy systems.',
    createdAt: '2024-02-03T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
    user: mockApplicantUsers[1],
  },
  {
    id: '13',
    userId: '13',
    title: 'Product Designer',
    location: 'Gəncə',
    expectedSalary: 2600,
    salaryCurrency: 'AZN',
    skills: ['Figma', 'Design Systems', 'UX Research', 'Prototyping', 'Mobile UI'],
    workExperience: [],
    education: [],
    languages: [],
    certifications: [],
    availability: 'immediate',
    workPreference: 'remote',
    profileCompleteness: 90,
    bio: 'Designer focused on product usability and premium mobile experiences.',
    createdAt: '2024-02-05T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
    user: mockApplicantUsers[2],
  },
];

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'Kapital Bank',
    industry: 'Maliyyə',
    description: 'Azərbaycanın aparıcı bankı. Müasir rəqəmsal bank xidmətləri və innovativ maliyyə həlləri.',
    logoUrl: mockCompanyLogoUrls.kapitalBank || buildCompanyLogoUrl('Kapital Bank', '2445A7'),
    website: 'https://kapitalbank.az',
    employeeCount: '1000-5000',
    location: 'Bakı',
    foundedYear: 1997,
    verificationStatus: 'verified',
    rating: 4.5,
    vacancyCount: 12,
    ownerId: '2',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '2',
    name: 'Azercell',
    industry: 'Telekommunikasiya',
    description: 'Azərbaycanın ən böyük mobil operator şirkəti.',
    logoUrl: mockCompanyLogoUrls.azercell || buildCompanyLogoUrl('Azercell', '6D28D9'),
    website: 'https://azercell.com',
    employeeCount: '1000-5000',
    location: 'Bakı',
    foundedYear: 1996,
    verificationStatus: 'verified',
    rating: 4.3,
    vacancyCount: 8,
    ownerId: '3',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '3',
    name: 'PASHA Holding',
    industry: 'Holdinq',
    description: 'Azərbaycanın aparıcı investisiya holdinqi.',
    logoUrl: mockCompanyLogoUrls.pashaHolding || buildCompanyLogoUrl('PASHA Holding', '0F766E'),
    website: 'https://pashaholding.az',
    employeeCount: '5000+',
    location: 'Bakı',
    foundedYear: 2006,
    verificationStatus: 'verified',
    rating: 4.7,
    vacancyCount: 15,
    ownerId: '4',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '4',
    name: 'ABB',
    industry: 'Maliyyə',
    description: 'Azərbaycan Beynəlxalq Bankı - ölkənin ən böyük dövlət bankı.',
    logoUrl: mockCompanyLogoUrls.abb || buildCompanyLogoUrl('ABB', 'B45309'),
    website: 'https://abb-bank.az',
    employeeCount: '1000-5000',
    location: 'Bakı',
    foundedYear: 1992,
    verificationStatus: 'verified',
    rating: 4.1,
    vacancyCount: 6,
    ownerId: '5',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Bravo Supermarket',
    industry: 'Pərakəndə satış',
    description: 'Azərbaycanın aparıcı supermarket şəbəkəsi.',
    logoUrl: mockCompanyLogoUrls.bravoSupermarket || buildCompanyLogoUrl('Bravo', 'DC2626'),
    website: 'https://bravo.az',
    employeeCount: '1000-5000',
    location: 'Bakı',
    foundedYear: 2007,
    verificationStatus: 'verified',
    rating: 3.9,
    vacancyCount: 20,
    ownerId: '6',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
];

export const mockVacancies: Vacancy[] = [
  {
    id: '1',
    title: 'Senior React Native Developer',
    description: 'We are looking for an experienced React Native developer to join our mobile banking team. You will be responsible for building and maintaining our flagship mobile application.',
    requirements: ['4+ years React Native experience', 'Strong TypeScript skills', 'Experience with state management', 'Knowledge of native modules', 'CI/CD experience'],
    responsibilities: ['Develop and maintain mobile application', 'Code review and mentoring', 'Collaborate with design team', 'Performance optimization', 'Write unit and integration tests'],
    benefits: ['Competitive salary', 'Health insurance', 'Remote work options', 'Professional development budget', 'Team building events'],
    salaryMin: 2500,
    salaryMax: 4000,
    salaryCurrency: 'AZN',
    showSalary: true,
    city: 'Bakı',
    workType: 'hybrid',
    experienceLevel: 'senior',
    skills: ['React Native', 'TypeScript', 'Redux', 'Jest', 'CI/CD'],
    companyId: '1',
    company: mockCompanies[0],
    status: 'active',
    applicantCount: 24,
    viewCount: 156,
    responseRate: 78,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '2',
    title: 'Product Manager',
    description: 'Join Azercell as a Product Manager and help shape the future of telecommunications in Azerbaijan.',
    requirements: ['3+ years product management experience', 'Strong analytical skills', 'Excellent communication', 'Agile methodology knowledge', 'Telecom industry experience preferred'],
    responsibilities: ['Define product roadmap', 'Conduct market research', 'Work with engineering teams', 'Analyze metrics and KPIs', 'Stakeholder management'],
    benefits: ['Competitive package', 'Corporate phone plan', 'Flexible hours', 'International training', 'Performance bonuses'],
    salaryMin: 2000,
    salaryMax: 3500,
    salaryCurrency: 'AZN',
    showSalary: true,
    city: 'Bakı',
    workType: 'onsite',
    experienceLevel: 'mid',
    skills: ['Product Management', 'Agile', 'Analytics', 'Communication', 'Strategy'],
    companyId: '2',
    company: mockCompanies[1],
    status: 'active',
    applicantCount: 45,
    viewCount: 320,
    responseRate: 65,
    createdAt: '2024-03-03T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    description: 'PASHA Holding is seeking a talented UI/UX Designer to create world-class digital experiences across our portfolio companies.',
    requirements: ['3+ years UI/UX design experience', 'Proficiency in Figma', 'Strong portfolio', 'Understanding of design systems', 'Mobile design experience'],
    responsibilities: ['Design mobile and web interfaces', 'Create and maintain design system', 'Conduct user research', 'Prototype and test designs', 'Collaborate with developers'],
    benefits: ['Premium salary', 'Health & dental insurance', 'Gym membership', 'Learning budget', 'Stock options'],
    salaryMin: 1800,
    salaryMax: 3000,
    salaryCurrency: 'AZN',
    showSalary: true,
    city: 'Bakı',
    workType: 'hybrid',
    experienceLevel: 'mid',
    skills: ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'],
    companyId: '3',
    company: mockCompanies[2],
    status: 'active',
    applicantCount: 38,
    viewCount: 280,
    responseRate: 72,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '4',
    title: 'Backend Developer (Node.js)',
    description: 'ABB is looking for a skilled Backend Developer to build and scale our digital banking infrastructure.',
    requirements: ['3+ years Node.js experience', 'PostgreSQL/MongoDB', 'REST & GraphQL APIs', 'Docker & Kubernetes', 'Security best practices'],
    responsibilities: ['Build microservices', 'Database design and optimization', 'API development', 'System monitoring', 'Documentation'],
    benefits: ['Competitive salary', 'Insurance package', 'Parking', 'Cafeteria', 'Career growth'],
    salaryMin: 2000,
    salaryMax: 3500,
    salaryCurrency: 'AZN',
    showSalary: true,
    city: 'Bakı',
    workType: 'onsite',
    experienceLevel: 'mid',
    skills: ['Node.js', 'PostgreSQL', 'Docker', 'TypeScript', 'GraphQL'],
    companyId: '4',
    company: mockCompanies[3],
    status: 'active',
    applicantCount: 19,
    viewCount: 145,
    responseRate: 80,
    createdAt: '2024-03-07T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '5',
    title: 'Data Analyst',
    description: 'Join Bravo as a Data Analyst and help us make data-driven decisions across our retail operations.',
    requirements: ['2+ years data analysis experience', 'SQL proficiency', 'Python/R knowledge', 'BI tools experience', 'Retail industry understanding'],
    responsibilities: ['Analyze sales and customer data', 'Create dashboards and reports', 'Support business decisions', 'Data quality assurance', 'Present findings to stakeholders'],
    benefits: ['Good salary', 'Employee discount', 'Health insurance', 'Transport support', 'Meal allowance'],
    salaryMin: 1200,
    salaryMax: 2000,
    salaryCurrency: 'AZN',
    showSalary: true,
    city: 'Bakı',
    workType: 'onsite',
    experienceLevel: 'junior',
    skills: ['SQL', 'Python', 'Power BI', 'Excel', 'Statistics'],
    companyId: '5',
    company: mockCompanies[4],
    status: 'active',
    applicantCount: 52,
    viewCount: 410,
    responseRate: 55,
    createdAt: '2024-03-08T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    description: 'Kapital Bank is looking for a DevOps Engineer to enhance our CI/CD pipelines and cloud infrastructure.',
    requirements: ['3+ years DevOps experience', 'AWS/Azure/GCP', 'Terraform/Ansible', 'Docker & Kubernetes', 'Linux administration'],
    responsibilities: ['Manage cloud infrastructure', 'Build CI/CD pipelines', 'Monitor system health', 'Security hardening', 'Disaster recovery planning'],
    benefits: ['Top market salary', 'Full insurance', 'Remote-first', 'Conference budget', 'Stock options'],
    salaryMin: 2800,
    salaryMax: 4500,
    salaryCurrency: 'AZN',
    showSalary: true,
    city: 'Bakı',
    workType: 'remote',
    experienceLevel: 'senior',
    skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'Linux'],
    companyId: '1',
    company: mockCompanies[0],
    status: 'active',
    applicantCount: 15,
    viewCount: 98,
    responseRate: 85,
    createdAt: '2024-03-09T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
];

export const mockApplications: Application[] = [
  {
    id: '1',
    vacancyId: '1',
    candidateId: '1',
    status: 'reviewed',
    subscriptionPlan: 'free',
    employerNotes: 'Looks aligned for mobile banking; confirm Expo and Supabase depth.',
    employerRating: 4,
    vacancy: mockVacancies[0],
    candidate: { ...mockCandidateProfile, user: mockUser },
    appliedAt: '2024-03-06T10:00:00Z',
    reviewedAt: '2024-03-08T10:00:00Z',
    updatedAt: '2024-03-08T10:00:00Z',
  },
  {
    id: '2',
    vacancyId: '3',
    candidateId: '1',
    status: 'pending',
    subscriptionPlan: 'pro',
    vacancy: mockVacancies[2],
    candidate: { ...mockCandidateProfile, user: mockUser },
    appliedAt: '2024-03-09T10:00:00Z',
    updatedAt: '2024-03-09T10:00:00Z',
  },
  {
    id: '3',
    vacancyId: '5',
    candidateId: '1',
    status: 'shortlisted',
    subscriptionPlan: 'premium',
    vacancy: mockVacancies[4],
    candidate: { ...mockCandidateProfile, user: mockUser },
    appliedAt: '2024-03-08T10:00:00Z',
    reviewedAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '4',
    vacancyId: '1',
    candidateId: '11',
    status: 'pending',
    subscriptionPlan: 'premium',
    vacancy: mockVacancies[0],
    candidate: mockApplicantProfiles[0],
    appliedAt: '2024-03-10T09:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
  },
  {
    id: '5',
    vacancyId: '6',
    candidateId: '12',
    status: 'shortlisted',
    subscriptionPlan: 'pro',
    employerNotes: 'Strong cloud background. Schedule technical interview.',
    employerRating: 5,
    vacancy: mockVacancies[5],
    candidate: mockApplicantProfiles[1],
    appliedAt: '2024-03-09T14:30:00Z',
    reviewedAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-03-10T11:00:00Z',
  },
  {
    id: '6',
    vacancyId: '1',
    candidateId: '13',
    status: 'reviewed',
    subscriptionPlan: 'free',
    vacancy: mockVacancies[0],
    candidate: mockApplicantProfiles[2],
    appliedAt: '2024-03-08T16:45:00Z',
    reviewedAt: '2024-03-09T09:30:00Z',
    updatedAt: '2024-03-09T09:30:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'application_update',
    title: 'Müraciətiniz baxıldı',
    body: 'Kapital Bank - Senior React Native Developer vakansiyasına müraciətiniz baxıldı.',
    data: { applicationId: '1', vacancyId: '1' },
    read: false,
    createdAt: '2024-03-10T09:00:00Z',
  },
  {
    id: '2',
    userId: '1',
    type: 'new_job_match',
    title: 'Yeni uyğun vakansiya',
    body: 'Azercell şirkətində sizə uyğun yeni vakansiya var.',
    data: { vacancyId: '2' },
    read: false,
    createdAt: '2024-03-10T08:00:00Z',
  },
  {
    id: '3',
    userId: '1',
    type: 'profile_reminder',
    title: 'Profilinizi tamamlayın',
    body: 'Profiliniz 85% tamamlanıb. Daha çox vakansiyaya uyğun gəlmək üçün tamamlayın.',
    read: true,
    createdAt: '2024-03-09T10:00:00Z',
  },
  {
    id: '4',
    userId: '1',
    type: 'application_update',
    title: 'Seçilmişlərə əlavə olundunuz',
    body: 'Bravo - Data Analyst vakansiyası üçün seçilmişlərə əlavə olundunuz.',
    data: { applicationId: '3', vacancyId: '5' },
    read: true,
    createdAt: '2024-03-09T08:00:00Z',
  },
];

export const mockEmployerAnalytics: AnalyticsSummary = {
  totalVacancies: 12,
  totalApplicants: 156,
  totalViews: 2340,
  weeklyApplicants: 28,
  shortlisted: 18,
  hired: 5,
  rejected: 42,
  responseRate: 78,
};
