// AUTO-GENERATED by scripts/generate-legal-content.mjs — do not edit by hand.
// Source of truth: docs/legal/*. Regenerate after any change there.

export interface LegalSection {
  heading?: string;
  paragraphs: string[];
}

export type LegalDocument = 'terms' | 'privacy';

export const legalContent: Record<'az' | 'en' | 'ru', Record<LegalDocument, LegalSection[]>> =
{
  "en": {
    "terms": [
      {
        "paragraphs": [
          "Effective date: [EFFECTIVE DATE]",
          "These Terms of Service (the \"Terms\") are a binding agreement between you and [AXTARIS MMC — registration pending; VÖEN: __________], a company registered in the Republic of Azerbaijan with its registered office at [REGISTERED ADDRESS] (\"AxtarIS\", \"we\", \"us\"). They govern your use of the AxtarIS mobile applications, the website axtaris.app, and all related services (together, the \"Service\").",
          "By creating an account or using the Service, you accept these Terms. If you do not agree, do not use the Service.",
          "If you use the Service on behalf of a company as an employer, the Employer Terms also apply to you and take precedence over these Terms where they conflict."
        ]
      },
      {
        "heading": "1. Definitions",
        "paragraphs": [
          "• \"Candidate\" — a natural person using the Service to search for work, create a professional profile, or apply to Vacancies.",
          "• \"Employer\" — a legal entity or entrepreneur using the Service to publish Vacancies, search for Candidates, or communicate with them.",
          "• \"Vacancy\" — a job advertisement published on the Service by an Employer.",
          "• \"User Content\" — any content you submit to the Service: profile details, CVs, applications, messages, images, company descriptions, Vacancies, and similar material.",
          "• \"Subscription\" — a paid plan that unlocks additional features, described in the Subscription & Refund Terms."
        ]
      },
      {
        "heading": "2. Eligibility",
        "paragraphs": [
          "You must be at least 16 years old to use the Service. By using the Service you confirm that you are 16 or older and, if you act for an Employer, that you are authorised to bind that Employer."
        ]
      },
      {
        "heading": "3. Your account",
        "paragraphs": [
          "3.1. You must provide accurate, current information when registering and keep it up to date. Profiles and CVs must describe you truthfully.",
          "3.2. You are responsible for keeping your credentials confidential and for all activity under your account. Tell us immediately at info@axtaris.app if you suspect unauthorised access.",
          "3.3. One person — one account. Creating accounts for someone else, impersonating others, or providing false identity information is prohibited."
        ]
      },
      {
        "heading": "4. What AxtarIS is — and what it is not",
        "paragraphs": [
          "4.1. AxtarIS is a platform that connects Candidates and Employers: it hosts Vacancies, professional profiles, applications, and messaging between the two sides.",
          "4.2. AxtarIS is not an employer, employment agency, or recruiter. We do not employ Candidates, we are not a party to any employment contract, interview, offer, or working relationship formed between a Candidate and an Employer, and we do not act as anyone's agent.",
          "4.3. We do not guarantee that any Candidate will receive interviews, offers, or employment, or that any Employer will find suitable candidates. Matching scores and recommendations are informational tools, not promises.",
          "4.4. Employers are independent parties. We do not verify every statement made in Vacancies or profiles. Exercise the same judgment you would anywhere else: never pay anyone to get a job, and report suspicious behaviour (see Section 7)."
        ]
      },
      {
        "heading": "5. Licence to use the app",
        "paragraphs": [
          "5.1. We grant you a personal, non-exclusive, non-transferable, revocable licence to install and use the AxtarIS applications and to access the Service, for the purposes described in these Terms.",
          "5.2. On Google Play and on the web, this Section is the end-user licence agreement for the app. On Apple's App Store, Apple's standard Licensed Application End User License Agreement applies to the app download itself; these Terms govern the Service.",
          "5.3. You may not copy, modify, distribute, sell, reverse-engineer, scrape, or extract data from the Service except as permitted by mandatory law, and you may not use the Service to build a competing database of vacancies or candidate profiles."
        ]
      },
      {
        "heading": "6. User Content",
        "paragraphs": [
          "6.1. You keep ownership of your User Content.",
          "6.2. You grant AxtarIS a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, adapt (for formatting), display, and transmit your User Content solely to operate, provide, secure, and improve the Service — for example, showing your profile to Employers you apply to, delivering your messages, or generating your CV preview. This licence ends when the content is deleted from the Service, except for backup copies kept for a limited period and content already lawfully delivered to other users (for example, an application an Employer has already received).",
          "6.3. You are responsible for your User Content. Do not submit content you have no right to share, and do not include other people's personal data without their permission.",
          "6.4. Special note for CVs and profiles: please do not include sensitive personal data (health, religion, political views, and similar categories) — the Service does not ask for it and does not need it. See the Privacy Policy."
        ]
      },
      {
        "heading": "7. Acceptable use and moderation",
        "paragraphs": [
          "7.1. The Community Guidelines are part of these Terms and define what is not allowed on the Service: among other things, fake vacancies, requesting fees from candidates, advance-fee and recruitment scams, pyramid/MLM schemes, discriminatory job requirements, harassment, and unlawful content.",
          "7.2. How moderation works. We use a combination of user reports, in-app reporting and blocking tools, and internal review by our team. When we are notified of — or otherwise identify — content that violates these Terms or the law, we may remove or restrict the content, warn the user, restrict features, or suspend or terminate the account, proportionately to the violation. Where practicable, we will tell you which content was affected and why, and how to object (write to info@axtaris.app). We respond to reports within the times stated in the Community Guidelines.",
          "7.3. We may preserve and disclose content where required by law or a lawful order of a competent authority."
        ]
      },
      {
        "heading": "8. Subscriptions and payments",
        "paragraphs": [
          "8.1. Parts of the Service are free. Paid Subscriptions unlock additional features for Candidates and Employers.",
          "8.2. Prices, billing periods, renewal, cancellation, and refunds are set out in the Subscription & Refund Terms, which form part of these Terms. In short: subscriptions renew automatically until cancelled; purchases made through Apple or Google are managed and refunded through them; purchases made on our website are processed by Paddle as merchant of record."
        ]
      },
      {
        "heading": "9. Third-party services",
        "paragraphs": [
          "The Service relies on third-party providers (hosting, push notifications, payment processing, AI-assisted text features). Their role in processing your data is described in the Privacy Policy. We are not responsible for third-party websites or services linked from Vacancies or messages."
        ]
      },
      {
        "heading": "10. Intellectual property",
        "paragraphs": [
          "The Service — including its software, design, logos, and databases, but excluding User Content — belongs to AxtarIS or its licensors. Nothing in these Terms transfers any of it to you. \"AxtarIS\" and associated marks may not be used without our written consent."
        ]
      },
      {
        "heading": "11. Availability and changes to the Service",
        "paragraphs": [
          "We work to keep the Service available and secure, but we do not promise uninterrupted or error-free operation. We may change, add, or discontinue features. If we discontinue the Service materially, we will give reasonable advance notice through the app or by email."
        ]
      },
      {
        "heading": "12. Disclaimers",
        "paragraphs": [
          "To the extent permitted by law, the Service is provided \"as is\" and \"as available\". We make no warranties about the accuracy of Vacancies, profiles, match scores, or AI-generated suggestions, and we do not warrant that the Service will meet your requirements."
        ]
      },
      {
        "heading": "13. Liability",
        "paragraphs": [
          "13.1. To the extent permitted by law, AxtarIS is not liable for: indirect or consequential losses; loss of profits, opportunities, or data; the conduct of Candidates or Employers (including hiring decisions, employment disputes, and content they publish); or events beyond our reasonable control.",
          "13.2. To the extent permitted by law, our total aggregate liability arising out of the Service in any 12-month period is limited to the greater of (a) the amounts you paid us for the Service in that period and (b) 100 AZN.",
          "13.3. Nothing in these Terms excludes or limits liability that cannot be excluded by law, including liability for intent or gross negligence, or for death or personal injury caused by negligence."
        ]
      },
      {
        "heading": "14. Your consumer rights",
        "paragraphs": [
          "Nothing in these Terms limits mandatory consumer rights in your country of residence. If you use the Service as a consumer in the European Union, the United Kingdom, or another jurisdiction with mandatory consumer protections, you keep the protections of that jurisdiction's law, and you may bring proceedings in your local courts where the law gives you that right."
        ]
      },
      {
        "heading": "15. Termination",
        "paragraphs": [
          "15.1. You may stop using the Service and delete your account at any time — in the app (Profile → Settings → Delete account) or via the web deletion page linked in the Privacy Policy.",
          "15.2. We may suspend or terminate your account for material or repeated violation of these Terms, for legal reasons, or where required to protect the Service or its users, following the moderation approach in Section 7. Where proportionate, we will warn you first.",
          "15.3. Before deleting your account you may export your data (CVs and profile data) using the tools in the app, or by requesting a copy at info@axtaris.app. What happens to your data after deletion is described in the Privacy Policy."
        ]
      },
      {
        "heading": "16. Changes to these Terms",
        "paragraphs": [
          "We may update these Terms. For material changes we will give at least 15 days' notice in the app or by email before the new version takes effect. If you do not agree with the changes, stop using the Service and delete your account before they take effect; continued use after that date means acceptance."
        ]
      },
      {
        "heading": "17. Governing law and disputes",
        "paragraphs": [
          "17.1. These Terms are governed by the laws of the Republic of Azerbaijan.",
          "17.2. Disputes are resolved by the competent courts of Baku, Azerbaijan — subject to Section 14: consumers with mandatory home-court rights keep them.",
          "17.3. Before going to court, please contact us at info@axtaris.app — most issues can be resolved directly."
        ]
      },
      {
        "heading": "18. Final provisions",
        "paragraphs": [
          "If any provision of these Terms is found invalid, the rest remain in force. These Terms, the Employer Terms (for Employers), the Privacy Policy, the Community Guidelines, and the Subscription & Refund Terms are the entire agreement between you and AxtarIS about the Service. We may assign this agreement as part of a merger or sale of the business; you may not assign it. Our not enforcing a provision is not a waiver.",
          "Contact",
          "AxtarIS — [AXTARIS MMC — registration pending; VÖEN: __________] [REGISTERED ADDRESS] Email: info@axtaris.app",
          "Related documents: Employer Terms, Privacy Policy, Community Guidelines, Subscription & Refund Terms."
        ]
      }
    ],
    "privacy": [
      {
        "paragraphs": [
          "Effective date: [EFFECTIVE DATE]",
          "This Privacy Policy explains how [AXTARIS MMC — registration pending; VÖEN: __________], [REGISTERED ADDRESS] (\"AxtarIS\", \"we\") processes personal data when you use the AxtarIS mobile applications, the website axtaris.app, and related services (the \"Service\").",
          "AxtarIS is the controller of the personal data described here, except where this Policy says otherwise (see Section 6 on Employers). Contact: info@axtaris.app.",
          "We wrote this Policy to satisfy the Law of the Republic of Azerbaijan \"On Personal Data\" (No. 998-IIIQ) and, because the Service is also available to users in the European Union and elsewhere, the EU General Data Protection Regulation (\"GDPR\") as the common high standard."
        ]
      },
      {
        "heading": "1. What data we collect",
        "paragraphs": [
          "Account data — name, email address, password (stored as a hash), phone number (optional), account role (candidate/employer), language preference.",
          "Candidate profile and CV data — work experience, education, skills, languages, certifications, expected salary, city, availability, profile photo, uploaded CV files, and data extracted from CVs you upload (see Section 8 on AI features).",
          "Employer data — company name, description, logo, registration details, contact persons, published vacancies.",
          "Applications and interactions — vacancies you apply to, screening-question answers, cover letters, saved jobs and searches, invitations, profile views.",
          "Messages — the content of chats between candidates and employers on the platform, including attached images, and support conversations.",
          "Payment data — your subscription plan and status, and transaction references. We never see or store full card numbers: payments are processed by Apple, Google, or Paddle (Section 7).",
          "Technical data — device type, operating system, app version, language, push notification token, IP address, and event logs (e.g. sign-in, errors) needed to run and secure the Service.",
          "Usage analytics — in-app events (e.g. screens viewed, applications sent) used in aggregate to improve the Service.",
          "We do not knowingly collect special categories of personal data (health, religion, political opinions, biometric data, etc.). Please do not put such information in your CV, profile, or messages — the Service does not ask for it and does not need it."
        ]
      },
      {
        "heading": "2. Why we process it (purposes and legal bases)",
        "paragraphs": [
          "| Purpose | Examples | Legal basis (GDPR) | |---|---|---| | Providing the Service | accounts, profiles, publishing vacancies, delivering applications and messages, matching suggestions | Contract (Art. 6(1)(b)) | | Payments and subscriptions | plan status, entitlements, receipts | Contract (Art. 6(1)(b)); legal obligation for accounting | | Safety and moderation | handling reports, blocking, preventing scams and fake vacancies | Legitimate interests (Art. 6(1)(f)) — keeping the platform safe | | Communications | service emails, push notifications about applications, messages, matches | Contract; consent for optional notifications (you control push permissions in your device settings) | | AI-assisted features | CV parsing, text suggestions you explicitly request | Contract — the feature you invoke | | Improvement and statistics | aggregated usage analytics, debugging | Legitimate interests (Art. 6(1)(f)) | | Legal compliance | responding to lawful requests, tax/accounting records | Legal obligation (Art. 6(1)(c)) |",
          "Under the Azerbaijani Law \"On Personal Data\", the primary basis for processing is your consent, given when you register (see Section 13), together with processing necessary to perform the contract you enter into with us."
        ]
      },
      {
        "heading": "3. Where your data lives",
        "paragraphs": [
          "The Service's database and file storage are hosted by Supabase in the [SUPABASE REGION — confirm in dashboard] region. If that region is outside your country, Section 9 (international transfers) applies."
        ]
      },
      {
        "heading": "4. Who receives your data — visibility inside the Service",
        "paragraphs": [
          "• Your candidate profile is visible to Employers in Talent Search according to your settings and plan features; your applications (profile, CV, answers, cover letter) are visible to the Employer whose vacancy you applied to.",
          "• Vacancies and company profiles are public to Service users.",
          "• Messages are visible to the participants of the conversation and, for support threads, to our support staff."
        ]
      },
      {
        "heading": "5. Who processes data for us (processors)",
        "paragraphs": [
          "We use a small set of service providers, bound by data processing agreements:",
          "| Provider | Role | Data | |---|---|---| | Supabase (hosting infrastructure) | database, authentication, file storage, serverless functions | all Service data | | Expo (push delivery) | delivering push notifications to your device | push token, notification content | | Paddle | payment processing for web purchases (as merchant of record — see Section 7) | purchase and billing data | | Apple / Google | in-app purchases, app distribution | purchase data per their policies | | OpenAI (via our secured proxy) | AI-assisted text features (Section 8) | the text you submit to those features | | Google Analytics | website usage analytics (Section 14), only after you accept the cookie banner | pseudonymous usage data (pages viewed, device/browser type) |",
          "We do not sell personal data and we do not share it with advertisers."
        ]
      },
      {
        "heading": "6. Employers are independent controllers",
        "paragraphs": [
          "When you apply to a vacancy or accept an invitation, the Employer receives your application data (profile, CV, answers, messages you send them). From that moment, the Employer processes that data as an independent controller for its own recruitment, under its own legal obligations. Our Employer Terms oblige Employers to use your data only for recruiting for the specific role, to protect it, and to delete it when recruitment ends or when you ask. For how a specific Employer handles your data, contact that Employer; we will help where we can (info@axtaris.app)."
        ]
      },
      {
        "heading": "7. Payments",
        "paragraphs": [
          "• In the apps, subscriptions are bought through Apple In-App Purchase or Google Play Billing. Apple/Google process the payment; we receive confirmation of the purchase and subscription status, never your card details.",
          "• On the web, purchases are processed by Paddle as merchant of record — Paddle is the seller of record for the transaction, handles payment data under its own privacy policy, and passes us the subscription status."
        ]
      },
      {
        "heading": "8. AI-assisted features",
        "paragraphs": [
          "Some features use AI language models (via OpenAI, through our controlled proxy): parsing an uploaded CV into profile fields, drafting or improving profile texts and cover letters, drafting job descriptions, and translations. The text you submit to these features is processed to provide the feature you requested and is not used by us — and, per our provider's terms, not used by the AI provider — to train AI models. Do not include other people's personal data or sensitive data in text you submit to AI features. AI output can be inaccurate; review it before using it."
        ]
      },
      {
        "heading": "9. International transfers",
        "paragraphs": [
          "Where personal data is transferred outside your jurisdiction (for example, to hosting or AI providers), we rely on the safeguards in our agreements with those providers, including the EU Standard Contractual Clauses where GDPR applies, and equivalent contractual protections otherwise."
        ]
      },
      {
        "heading": "10. How long we keep data (retention)",
        "paragraphs": [
          "| Data | Retention | |---|---| | Account, profile, CV data | while your account exists; deleted within 30 days of account deletion | | Applications delivered to Employers | your copy is deleted with your account; the Employer's copy is governed by the Employer's obligations (Section 6) | | Messages | while your account exists; on deletion your identity is removed from conversations | | Payment/transaction records | as long as tax and accounting law requires (typically 5 years) | | Technical logs | up to 12 months | | Backups | rolling backups expire within 30 days of the deletion propagating |"
        ]
      },
      {
        "heading": "11. Your rights",
        "paragraphs": [
          "You have the right to: access your data and get a copy; correct inaccurate data; delete your data; restrict or object to processing based on legitimate interests; withdraw consent at any time (without affecting prior processing); and data portability for data you provided (machine-readable export).",
          "To exercise any right, use the in-app tools or write to info@axtaris.app. We respond within 30 days. If you are in the EU/EEA or UK, you may also lodge a complaint with your local supervisory authority; in Azerbaijan, with the authority responsible for personal data oversight."
        ]
      },
      {
        "heading": "12. Deleting your account",
        "paragraphs": [
          "• In the app: Profile → Settings → Delete account. This permanently deletes your account and the data listed in Section 10.",
          "• On the web: https://axtaris.app/legal/delete-account — for deletion without reinstalling the app.",
          "Deletion is permanent; we cannot restore a deleted account."
        ]
      },
      {
        "heading": "13. Consent statement (Azerbaijan Law No. 998-IIIQ)",
        "paragraphs": [
          "By registering, you consent to the processing of your personal data by [AXTARIS MMC — registration pending; VÖEN: __________] (operator) for the purposes in Section 2 (providing the job-platform Service and the related purposes listed). The consent is valid while your account exists; you may withdraw it at any time by deleting your account (Section 12) or writing to info@axtaris.app, after which your data is deleted or archived as described in Section 10. Providing data marked optional is voluntary; core account data is required to provide the Service."
        ]
      },
      {
        "heading": "14. Cookies (website)",
        "paragraphs": [
          "The axtaris.app website uses strictly necessary cookies/storage (e.g. language preference, your cookie choice) at all times.",
          "We also use Google Analytics 4 to understand aggregate site usage (pages viewed, waitlist signups). Analytics cookies (_ga, _ga_*, expiring after up to 14 months) are set only if you accept the cookie banner shown on your first visit; until you accept, Google Consent Mode keeps analytics storage denied. You can withdraw your choice at any time by clearing your browser's site data for axtaris.app, which brings the banner back. We do not run advertising or cross-site tracking cookies, and Google does not receive your name or email through this integration."
        ]
      },
      {
        "heading": "15. Children",
        "paragraphs": [
          "The Service is for users 16 and older. We do not knowingly process data of children under 16; if you believe a child is using the Service, tell us at info@axtaris.app and we will remove the account."
        ]
      },
      {
        "heading": "16. Security",
        "paragraphs": [
          "We protect data with encryption in transit, access controls and row-level security in our database, secrets management, and the principle of least privilege for staff access. No system is perfectly secure; if a breach affects your data, we will notify you and the competent authorities as the law requires (including the GDPR's 72-hour authority notification where applicable)."
        ]
      },
      {
        "heading": "17. Push notifications",
        "paragraphs": [
          "Push notifications (new messages, application updates, matches) are optional — the app asks for permission, and you can revoke it any time in device settings. We store your push token to deliver them and delete it when you sign out or delete the account."
        ]
      },
      {
        "heading": "18. Changes to this Policy",
        "paragraphs": [
          "We may update this Policy. Material changes will be announced in the app or by email at least 15 days before taking effect. The current version is always available in the app (Legal) and at axtaris.app.",
          "Contact",
          "AxtarIS — [AXTARIS MMC — registration pending; VÖEN: __________] [REGISTERED ADDRESS] Email: info@axtaris.app",
          "Related documents: Terms of Service, Employer Terms, Community Guidelines, Subscription & Refund Terms."
        ]
      }
    ]
  },
  "az": {
    "terms": [
      {
        "paragraphs": [
          "Qüvvəyə minmə tarixi: [QÜVVƏYƏ MİNMƏ TARİXİ]",
          "Bu İstifadə Şərtləri (\"Şərtlər\") sizinlə Azərbaycan Respublikasında qeydiyyatdan keçmiş, hüquqi ünvanı [QEYDİYYAT ÜNVANI] olan [AXTARIS MMC — qeydiyyat gözlənilir; VÖEN: __________] (\"AxtarIS\", \"biz\") arasında məcburi hüquqi qüvvəyə malik müqavilədir. Şərtlər AxtarIS mobil tətbiqlərindən, axtaris.app saytından və onlarla bağlı bütün xidmətlərdən (birlikdə — \"Xidmət\") istifadənizi tənzimləyir.",
          "Hesab yaratmaqla və ya Xidmətdən istifadə etməklə bu Şərtləri qəbul edirsiniz. Razı deyilsinizsə, Xidmətdən istifadə etməyin.",
          "Xidmətdən işəgötürən qismində bir şirkət adından istifadə edirsinizsə, sizə həmçinin İşəgötürən Şərtləri tətbiq olunur və ziddiyyət olduqda üstünlük onlara verilir."
        ]
      },
      {
        "heading": "1. Anlayışlar",
        "paragraphs": [
          "• \"Namizəd\" — iş axtarmaq, peşəkar profil yaratmaq və ya Vakansiyalara müraciət etmək üçün Xidmətdən istifadə edən fiziki şəxs.",
          "• \"İşəgötürən\" — Vakansiya dərc etmək, Namizəd axtarmaq və ya onlarla əlaqə qurmaq üçün Xidmətdən istifadə edən hüquqi şəxs və ya sahibkar.",
          "• \"Vakansiya\" — İşəgötürən tərəfindən Xidmətdə dərc olunan iş elanı.",
          "• \"İstifadəçi Məzmunu\" — Xidmətə təqdim etdiyiniz istənilən məzmun: profil məlumatları, CV-lər, müraciətlər, mesajlar, şəkillər, şirkət təsvirləri, Vakansiyalar və bənzər materiallar.",
          "• \"Abunəlik\" — Abunəlik və Geri Ödəniş Şərtlərində təsvir olunan, əlavə funksiyalar açan ödənişli plan."
        ]
      },
      {
        "heading": "2. İstifadə hüququ",
        "paragraphs": [
          "Xidmətdən istifadə üçün ən azı 16 yaşınız olmalıdır. Xidmətdən istifadə etməklə 16 yaşdan yuxarı olduğunuzu, İşəgötürən adından çıxış edirsinizsə, həmin İşəgötürəni təmsil etmək səlahiyyətinizin olduğunu təsdiq edirsiniz."
        ]
      },
      {
        "heading": "3. Hesabınız",
        "paragraphs": [
          "3.1. Qeydiyyat zamanı düzgün və aktual məlumat verməli və onu yenilənmiş saxlamalısınız. Profil və CV-lər sizi doğru təsvir etməlidir.",
          "3.2. Giriş məlumatlarınızın məxfiliyinə və hesabınız altında baş verən bütün fəaliyyətə görə siz cavabdehsiniz. İcazəsiz girişdən şübhələnirsinizsə, dərhal info@axtaris.app ünvanına yazın.",
          "3.3. Bir şəxs — bir hesab. Başqası üçün hesab yaratmaq, başqasını təqlid etmək və ya yanlış şəxsiyyət məlumatı vermək qadağandır."
        ]
      },
      {
        "heading": "4. AxtarIS nədir — və nə deyil",
        "paragraphs": [
          "4.1. AxtarIS Namizədlərlə İşəgötürənləri birləşdirən platformadır: Vakansiyaları, peşəkar profilləri, müraciətləri və tərəflər arasında yazışmanı yerləşdirir.",
          "4.2. AxtarIS işəgötürən, məşğulluq agentliyi və ya işə götürən şirkət deyil. Biz Namizədləri işə götürmürük, Namizədlə İşəgötürən arasında yaranan heç bir əmək müqaviləsinin, müsahibənin, təklifin və ya əmək münasibətinin tərəfi deyilik və heç kimin agenti kimi çıxış etmirik.",
          "4.3. Heç bir Namizədə müsahibə, təklif və ya iş, heç bir İşəgötürənə uyğun namizəd tapacağına zəmanət vermirik. Uyğunluq balları və tövsiyələr məlumat xarakterli alətlərdir, vəd deyil.",
          "4.4. İşəgötürənlər müstəqil tərəflərdir. Vakansiya və profillərdəki hər ifadəni yoxlamırıq. Hər yerdə olduğu kimi diqqətli olun: iş tapmaq üçün heç vaxt heç kimə pul ödəməyin və şübhəli davranış barədə bizə bildirin (bax: 7-ci bölmə)."
        ]
      },
      {
        "heading": "5. Tətbiqdən istifadə lisenziyası",
        "paragraphs": [
          "5.1. Sizə AxtarIS tətbiqlərini quraşdırmaq və Xidmətdən bu Şərtlərdə göstərilən məqsədlərlə istifadə etmək üçün şəxsi, müstəsna olmayan, ötürülə bilməyən, geri çağırıla bilən lisenziya veririk.",
          "5.2. Google Play-də və vebdə bu bölmə tətbiq üçün son istifadəçi lisenziya müqaviləsi rolunu oynayır. Apple App Store-da tətbiqin yüklənməsinə Apple-ın standart Lisenziyalı Tətbiq Son İstifadəçi Lisenziya Müqaviləsi tətbiq olunur; Xidməti isə bu Şərtlər tənzimləyir.",
          "5.3. Məcburi qanunvericiliyin icazə verdiyi hallar istisna olmaqla, Xidməti kopyalamaq, dəyişdirmək, yaymaq, satmaq, tərsinə mühəndislik etmək, avtomatik yolla məlumat toplamaq (scraping) qadağandır; Xidmətdən rəqib vakansiya və ya namizəd bazası yaratmaq üçün istifadə etmək olmaz."
        ]
      },
      {
        "heading": "6. İstifadəçi Məzmunu",
        "paragraphs": [
          "6.1. İstifadəçi Məzmununuz üzərində mülkiyyət sizdə qalır.",
          "6.2. AxtarIS-ə İstifadəçi Məzmununuzu yalnız Xidməti işlətmək, təqdim etmək, qorumaq və təkmilləşdirmək üçün yerləşdirmək, saxlamaq, çoxaltmaq, (formatlaşdırma məqsədilə) uyğunlaşdırmaq, göstərmək və ötürmək üçün müstəsna olmayan, ərazi məhdudiyyətsiz, ödənişsiz lisenziya verirsiniz — məsələn, müraciət etdiyiniz İşəgötürənə profilinizi göstərmək, mesajlarınızı çatdırmaq və ya CV önizləməsini yaratmaq üçün. Bu lisenziya məzmun Xidmətdən silindikdə bitir; məhdud müddət saxlanan ehtiyat nüsxələri və artıq qanuni şəkildə digər istifadəçilərə çatdırılmış məzmun (məsələn, İşəgötürənin artıq aldığı müraciət) istisnadır.",
          "6.3. İstifadəçi Məzmununa görə siz cavabdehsiniz. Paylaşmaq hüququnuz olmayan məzmun təqdim etməyin və başqalarının fərdi məlumatlarını icazəsiz daxil etməyin.",
          "6.4. CV və profillər üçün xüsusi qeyd: həssas fərdi məlumatları (səhhət, din, siyasi baxışlar və s.) daxil etməyin — Xidmət bunları soruşmur və onlara ehtiyac yoxdur. Bax: Məxfilik Siyasəti."
        ]
      },
      {
        "heading": "7. Yolverilən istifadə və moderasiya",
        "paragraphs": [
          "7.1. İcma Qaydaları bu Şərtlərin tərkib hissəsidir və Xidmətdə nələrin qadağan olduğunu müəyyən edir: o cümlədən saxta vakansiyalar, namizədlərdən ödəniş tələb etmək, avans-ödənişli fırıldaqlar, piramida/MLM sxemləri, ayrı-seçkilik yaradan tələblər, təqib və qanunazidd məzmun.",
          "7.2. Moderasiya necə işləyir. İstifadəçi şikayətlərindən, tətbiqdaxili şikayət və bloklama alətlərindən və komandamızın daxili yoxlamasından istifadə edirik. Bu Şərtləri və ya qanunu pozan məzmun barədə məlumat aldıqda və ya onu özümüz aşkar etdikdə, pozuntuya mütənasib şəkildə məzmunu silə və ya məhdudlaşdıra, istifadəçiyə xəbərdarlıq edə, funksiyaları məhdudlaşdıra, hesabı dayandıra və ya ləğv edə bilərik. Mümkün olduqda hansı məzmuna və nə üçün tədbir görüldüyünü, etiraz qaydasını bildiririk (info@axtaris.app ünvanına yazın). Şikayətlərə İcma Qaydalarında göstərilən müddətlərdə baxırıq.",
          "7.3. Qanunla və ya səlahiyyətli orqanın qanuni tələbi ilə məzmunu saxlaya və təqdim edə bilərik."
        ]
      },
      {
        "heading": "8. Abunəliklər və ödənişlər",
        "paragraphs": [
          "8.1. Xidmətin bir hissəsi pulsuzdur. Ödənişli Abunəliklər Namizədlər və İşəgötürənlər üçün əlavə funksiyalar açır.",
          "8.2. Qiymətlər, ödəniş dövrləri, yenilənmə, ləğvetmə və geri ödənişlər bu Şərtlərin tərkib hissəsi olan Abunəlik və Geri Ödəniş Şərtlərində göstərilib. Qısaca: abunəliklər ləğv edilənədək avtomatik yenilənir; Apple və ya Google vasitəsilə edilən alışlar onlar tərəfindən idarə olunur və geri qaytarılır; saytımızdakı alışlar rəsmi satıcı (merchant of record) qismində Paddle tərəfindən emal olunur."
        ]
      },
      {
        "heading": "9. Üçüncü tərəf xidmətləri",
        "paragraphs": [
          "Xidmət üçüncü tərəf təchizatçılarına (hostinq, push bildirişlər, ödəniş emalı, süni intellekt əsaslı mətn funksiyaları) əsaslanır. Onların məlumatlarınızın emalındakı rolu Məxfilik Siyasətində təsvir olunub. Vakansiya və mesajlardan keçid verilən kənar sayt və xidmətlərə görə cavabdeh deyilik."
        ]
      },
      {
        "heading": "10. Əqli mülkiyyət",
        "paragraphs": [
          "Xidmət — proqram təminatı, dizayn, loqolar və verilənlər bazaları daxil olmaqla, İstifadəçi Məzmunu istisna olmaqla — AxtarIS-ə və ya lisenziya verənlərinə məxsusdur. Bu Şərtlər onların heç birini sizə ötürmür. \"AxtarIS\" adı və əlaqəli nişanlar yazılı razılığımız olmadan istifadə edilə bilməz."
        ]
      },
      {
        "heading": "11. Əlçatanlıq və Xidmətdə dəyişikliklər",
        "paragraphs": [
          "Xidməti əlçatan və təhlükəsiz saxlamağa çalışırıq, lakin fasiləsiz və xətasız işləyəcəyini vəd etmirik. Funksiyaları dəyişdirə, əlavə edə və ya dayandıra bilərik. Xidməti əhəmiyyətli dərəcədə dayandırsaq, tətbiq və ya e-poçt vasitəsilə əvvəlcədən ağlabatan müddətdə xəbər verəcəyik."
        ]
      },
      {
        "heading": "12. Məsuliyyətdən imtina",
        "paragraphs": [
          "Qanunun icazə verdiyi həddə Xidmət \"olduğu kimi\" və \"mövcud olduğu kimi\" təqdim olunur. Vakansiyaların, profillərin, uyğunluq ballarının və ya süni intellekt təkliflərinin dəqiqliyinə zəmanət vermirik."
        ]
      },
      {
        "heading": "13. Məsuliyyət",
        "paragraphs": [
          "13.1. Qanunun icazə verdiyi həddə AxtarIS aşağıdakılara görə məsuliyyət daşımır: dolayı və ya nəticə etibarilə yaranan zərərlər; mənfəət, imkan və ya məlumat itkisi; Namizədlərin və İşəgötürənlərin davranışı (işə qəbul qərarları, əmək mübahisələri və dərc etdikləri məzmun daxil olmaqla); ağlabatan nəzarətimizdən kənar hadisələr.",
          "13.2. Qanunun icazə verdiyi həddə istənilən 12 aylıq dövrdə Xidmətlə bağlı ümumi məsuliyyətimiz (a) həmin dövrdə bizə ödədiyiniz məbləğlərdən və (b) 100 AZN-dən böyük olanı ilə məhdudlaşır.",
          "13.3. Bu Şərtlərdə heç nə qanunla istisna edilə bilməyən məsuliyyəti — o cümlədən qəsd və ya kobud ehtiyatsızlıq, habelə ehtiyatsızlıq nəticəsində həyata və sağlamlığa vurulan zərərə görə məsuliyyəti — istisna etmir."
        ]
      },
      {
        "heading": "14. İstehlakçı hüquqlarınız",
        "paragraphs": [
          "Bu Şərtlərdə heç nə yaşadığınız ölkənin məcburi istehlakçı hüquqlarını məhdudlaşdırmır. Avropa İttifaqında, Birləşmiş Krallıqda və ya məcburi istehlakçı müdafiəsi olan başqa yurisdiksiyada istehlakçı kimi istifadə edirsinizsə, həmin ölkənin qanunvericiliyinin verdiyi müdafiələr sizdə qalır və qanun belə hüquq verdikdə yerli məhkəmələrə müraciət edə bilərsiniz."
        ]
      },
      {
        "heading": "15. Xitam",
        "paragraphs": [
          "15.1. İstənilən vaxt Xidmətdən istifadəni dayandıra və hesabınızı silə bilərsiniz — tətbiqdə (Profil → Parametrlər → Hesabı sil) və ya Məxfilik Siyasətində göstərilən veb səhifə vasitəsilə.",
          "15.2. Bu Şərtlərin əhəmiyyətli və ya təkrar pozuntusuna görə, hüquqi səbəblərdən və ya Xidməti və istifadəçiləri qorumaq zərurəti yarandıqda, 7-ci bölmədəki moderasiya yanaşmasına uyğun olaraq hesabınızı dayandıra və ya ləğv edə bilərik. Mütənasib olduqda əvvəlcə xəbərdarlıq edirik.",
          "15.3. Hesabı silməzdən əvvəl məlumatlarınızı (CV və profil məlumatları) tətbiqdəki alətlərlə ixrac edə və ya info@axtaris.app ünvanından surət tələb edə bilərsiniz. Silinmədən sonra məlumatların taleyi Məxfilik Siyasətində təsvir olunub."
        ]
      },
      {
        "heading": "16. Şərtlərdə dəyişikliklər",
        "paragraphs": [
          "Bu Şərtləri yeniləyə bilərik. Əhəmiyyətli dəyişikliklər qüvvəyə minməzdən ən azı 15 gün əvvəl tətbiqdə və ya e-poçtla elan olunur. Dəyişikliklərlə razı deyilsinizsə, onlar qüvvəyə minənədək istifadəni dayandırıb hesabınızı silin; həmin tarixdən sonra istifadənin davamı qəbul deməkdir."
        ]
      },
      {
        "heading": "17. Tətbiq olunan hüquq və mübahisələr",
        "paragraphs": [
          "17.1. Bu Şərtlər Azərbaycan Respublikasının qanunvericiliyi ilə tənzimlənir.",
          "17.2. Mübahisələr Bakı şəhərinin səlahiyyətli məhkəmələrində həll olunur — 14-cü bölmə nəzərə alınmaqla: məcburi yerli məhkəmə hüquqları olan istehlakçılar həmin hüquqları saxlayır.",
          "17.3. Məhkəməyə müraciətdən əvvəl info@axtaris.app ünvanına yazın — məsələlərin çoxu birbaşa həll oluna bilir."
        ]
      },
      {
        "heading": "18. Yekun müddəalar",
        "paragraphs": [
          "Şərtlərin hər hansı müddəası etibarsız sayılarsa, qalanları qüvvədə qalır. Bu Şərtlər, İşəgötürən Şərtləri (İşəgötürənlər üçün), Məxfilik Siyasəti, İcma Qaydaları və Abunəlik və Geri Ödəniş Şərtləri Xidmətlə bağlı sizinlə AxtarIS arasında tam razılaşmadır. Biz bu müqaviləni birləşmə və ya biznesin satışı çərçivəsində ötürə bilərik; siz ötürə bilməzsiniz. Hər hansı müddəanı tətbiq etməməyimiz ondan imtina deyil.",
          "Əlaqə",
          "AxtarIS — [AXTARIS MMC — qeydiyyat gözlənilir; VÖEN: __________] [QEYDİYYAT ÜNVANI] E-poçt: info@axtaris.app",
          "Əlaqəli sənədlər: İşəgötürən Şərtləri, Məxfilik Siyasəti, İcma Qaydaları, Abunəlik və Geri Ödəniş Şərtləri."
        ]
      }
    ],
    "privacy": [
      {
        "paragraphs": [
          "Qüvvəyə minmə tarixi: [QÜVVƏYƏ MİNMƏ TARİXİ]",
          "Bu Məxfilik Siyasəti [AXTARIS MMC — qeydiyyat gözlənilir; VÖEN: __________], [QEYDİYYAT ÜNVANI] (\"AxtarIS\", \"biz\") tərəfindən AxtarIS mobil tətbiqlərindən, axtaris.app saytından və əlaqəli xidmətlərdən (\"Xidmət\") istifadə zamanı fərdi məlumatların necə emal olunduğunu izah edir.",
          "Bu sənəddə başqa hal göstərilməyibsə (İşəgötürənlər barədə 6-cı bölməyə baxın), burada təsvir olunan fərdi məlumatların operatoru (nəzarətçisi) AxtarIS-dir. Əlaqə: info@axtaris.app.",
          "Bu Siyasət Azərbaycan Respublikasının \"Fərdi məlumatlar haqqında\" Qanununa (№ 998-IIIQ) və — Xidmət Avropa İttifaqı və digər ölkələrin istifadəçiləri üçün də əlçatan olduğundan — ümumi yüksək standart kimi Aİ Ümumi Məlumatların Qorunması Reqlamentinə (\"GDPR\") uyğun tərtib olunub."
        ]
      },
      {
        "heading": "1. Hansı məlumatları toplayırıq",
        "paragraphs": [
          "Hesab məlumatları — ad, e-poçt ünvanı, şifrə (heş şəklində saxlanılır), telefon nömrəsi (istəyə bağlı), hesab rolu (namizəd/işəgötürən), dil seçimi.",
          "Namizəd profili və CV məlumatları — iş təcrübəsi, təhsil, bacarıqlar, dillər, sertifikatlar, gözlənilən əməkhaqqı, şəhər, əlçatanlıq, profil şəkli, yüklənmiş CV faylları və yüklədiyiniz CV-lərdən çıxarılan məlumatlar (süni intellekt funksiyaları barədə 8-ci bölməyə baxın).",
          "İşəgötürən məlumatları — şirkət adı, təsviri, loqo, qeydiyyat məlumatları, əlaqə şəxsləri, dərc olunmuş vakansiyalar.",
          "Müraciətlər və qarşılıqlı əlaqələr — müraciət etdiyiniz vakansiyalar, seçmə suallarına cavablar, motivasiya məktubları, yadda saxlanmış işlər və axtarışlar, dəvətlər, profilə baxışlar.",
          "Mesajlar — platformada namizədlərlə işəgötürənlər arasında yazışmaların məzmunu, əlavə olunmuş şəkillər daxil olmaqla, habelə dəstək yazışmaları.",
          "Ödəniş məlumatları — abunəlik planınız və statusu, əməliyyat istinadları. Kart nömrələrini heç vaxt görmürük və saxlamırıq: ödənişlər Apple, Google və ya Paddle tərəfindən emal olunur (7-ci bölmə).",
          "Texniki məlumatlar — cihaz növü, əməliyyat sistemi, tətbiq versiyası, dil, push bildiriş tokeni, IP ünvanı və Xidmətin işlədilməsi və qorunması üçün lazım olan hadisə qeydləri (məsələn, giriş, xətalar).",
          "İstifadə analitikası — Xidməti təkmilləşdirmək üçün ümumiləşdirilmiş şəkildə istifadə olunan tətbiqdaxili hadisələr (məsələn, baxılan ekranlar, göndərilən müraciətlər).",
          "Fərdi məlumatların xüsusi kateqoriyalarını (səhhət, din, siyasi baxışlar, biometrik məlumatlar və s.) bilərəkdən toplamırıq. Belə məlumatları CV-nizə, profilinizə və ya mesajlarınıza daxil etməyin — Xidmət bunları soruşmur və onlara ehtiyacı yoxdur."
        ]
      },
      {
        "heading": "2. Nə üçün emal edirik (məqsədlər və hüquqi əsaslar)",
        "paragraphs": [
          "| Məqsəd | Nümunələr | Hüquqi əsas (GDPR) | |---|---|---| | Xidmətin göstərilməsi | hesablar, profillər, vakansiyaların dərci, müraciət və mesajların çatdırılması, uyğunluq təklifləri | Müqavilə (mad. 6(1)(b)) | | Ödənişlər və abunəliklər | plan statusu, funksiya hüquqları, qəbzlər | Müqavilə; mühasibat üzrə hüquqi öhdəlik | | Təhlükəsizlik və moderasiya | şikayətlərə baxılması, bloklama, fırıldaq və saxta vakansiyaların qarşısının alınması | Qanuni maraqlar (mad. 6(1)(f)) — platformanın təhlükəsizliyi | | Kommunikasiyalar | xidmət e-poçtları, müraciət, mesaj və uyğunluqlar barədə push bildirişlər | Müqavilə; istəyə bağlı bildirişlər üçün razılıq (push icazələrini cihaz parametrlərində idarə edirsiniz) | | Süni intellekt funksiyaları | CV emalı, açıq şəkildə tələb etdiyiniz mətn təklifləri | Müqavilə — çağırdığınız funksiya | | Təkmilləşdirmə və statistika | ümumiləşdirilmiş analitika, sazlama | Qanuni maraqlar (mad. 6(1)(f)) | | Hüquqi uyğunluq | qanuni sorğulara cavab, vergi/mühasibat sənədləri | Hüquqi öhdəlik (mad. 6(1)(c)) |",
          "Azərbaycan Respublikasının \"Fərdi məlumatlar haqqında\" Qanununa əsasən emalın əsas əsası qeydiyyat zamanı verdiyiniz razılığınız (13-cü bölməyə baxın) və bizimlə bağladığınız müqavilənin icrası üçün zəruri emaldır."
        ]
      },
      {
        "heading": "3. Məlumatlarınız harada saxlanılır",
        "paragraphs": [
          "Xidmətin verilənlər bazası və fayl anbarı Supabase tərəfindən [SUPABASE REGİONU — idarəetmə panelində dəqiqləşdirin] regionunda yerləşdirilir. Bu region ölkənizdən kənardadırsa, 9-cu bölmə (beynəlxalq ötürmələr) tətbiq olunur."
        ]
      },
      {
        "heading": "4. Məlumatlarınızı kim görür — Xidmət daxilində görünürlük",
        "paragraphs": [
          "• Namizəd profiliniz parametrlərinizə və plan funksiyalarına uyğun olaraq Talent Axtarışında İşəgötürənlərə görünür; müraciətləriniz (profil, CV, cavablar, motivasiya məktubu) müraciət etdiyiniz vakansiyanın İşəgötürəninə görünür.",
          "• Vakansiyalar və şirkət profilləri Xidmət istifadəçiləri üçün açıqdır.",
          "• Mesajlar söhbətin iştirakçılarına, dəstək yazışmaları isə həmçinin dəstək əməkdaşlarımıza görünür."
        ]
      },
      {
        "heading": "5. Məlumatları bizim üçün kim emal edir (emalçılar)",
        "paragraphs": [
          "Məlumat emalı müqavilələri ilə bağlı olan məhdud sayda xidmət təchizatçısından istifadə edirik:",
          "| Təchizatçı | Rolu | Məlumatlar | |---|---|---| | Supabase (hostinq infrastrukturu) | verilənlər bazası, autentifikasiya, fayl anbarı, server funksiyaları | bütün Xidmət məlumatları | | Expo (push çatdırılması) | push bildirişlərin cihazınıza çatdırılması | push tokeni, bildiriş məzmunu | | Paddle | veb alışların ödəniş emalı (rəsmi satıcı — merchant of record, 7-ci bölmə) | alış və hesablaşma məlumatları | | Apple / Google | tətbiqdaxili alışlar, tətbiq paylanması | öz siyasətlərinə uyğun alış məlumatları | | OpenAI (qorunan proksimiz vasitəsilə) | süni intellekt mətn funksiyaları (8-ci bölmə) | həmin funksiyalara təqdim etdiyiniz mətn | | Google Analytics | sayt istifadəsi analitikası (14-cü bölmə), yalnız cookie bannerini qəbul etdikdən sonra | psevdonimləşdirilmiş istifadə məlumatları (baxılan səhifələr, cihaz/brauzer növü) |",
          "Fərdi məlumatları satmırıq və reklamçılarla paylaşmırıq."
        ]
      },
      {
        "heading": "6. İşəgötürənlər müstəqil operatorlardır",
        "paragraphs": [
          "Vakansiyaya müraciət etdikdə və ya dəvəti qəbul etdikdə İşəgötürən müraciət məlumatlarınızı (profil, CV, cavablar, ona göndərdiyiniz mesajlar) alır. Həmin andan İşəgötürən bu məlumatları öz işə qəbulu üçün, öz hüquqi öhdəlikləri altında müstəqil operator kimi emal edir. İşəgötürən Şərtlərimiz İşəgötürənləri məlumatlarınızdan yalnız konkret vəzifə üzrə işə qəbul üçün istifadə etməyə, onları qorumağa, işə qəbul bitdikdə və ya siz tələb etdikdə silməyə məcbur edir. Konkret İşəgötürənin məlumatlarınızla necə davrandığı barədə həmin İşəgötürənə müraciət edin; bacardığımız qədər kömək edərik (info@axtaris.app)."
        ]
      },
      {
        "heading": "7. Ödənişlər",
        "paragraphs": [
          "• Tətbiqlərdə abunəliklər Apple tətbiqdaxili alış və ya Google Play Billing vasitəsilə alınır. Ödənişi Apple/Google emal edir; biz yalnız alışın təsdiqini və abunəlik statusunu alırıq, kart məlumatlarınızı heç vaxt görmürük.",
          "• Vebdə alışlar rəsmi satıcı qismində Paddle tərəfindən emal olunur — əməliyyat üzrə satıcı Paddle-dır, ödəniş məlumatlarını öz məxfilik siyasəti əsasında idarə edir və bizə abunəlik statusunu ötürür."
        ]
      },
      {
        "heading": "8. Süni intellekt funksiyaları",
        "paragraphs": [
          "Bəzi funksiyalar süni intellekt dil modellərindən istifadə edir (OpenAI, nəzarət etdiyimiz proksi vasitəsilə): yüklənmiş CV-nin profil sahələrinə çevrilməsi, profil mətnləri və motivasiya məktublarının tərtibi/təkmilləşdirilməsi, vakansiya təsvirlərinin tərtibi, tərcümələr. Bu funksiyalara təqdim etdiyiniz mətn tələb etdiyiniz funksiyanı təmin etmək üçün emal olunur və nə bizim tərəfimizdən, nə də — təchizatçımızın şərtlərinə əsasən — süni intellekt təchizatçısı tərəfindən modellərin öyrədilməsi üçün istifadə edilmir. Süni intellekt funksiyalarına başqalarının fərdi məlumatlarını və həssas məlumatları daxil etməyin. Süni intellekt nəticələri qeyri-dəqiq ola bilər; istifadə etməzdən əvvəl yoxlayın."
        ]
      },
      {
        "heading": "9. Beynəlxalq ötürmələr",
        "paragraphs": [
          "Fərdi məlumatlar yurisdiksiyanızdan kənara ötürüldükdə (məsələn, hostinq və ya süni intellekt təchizatçılarına), həmin təchizatçılarla müqavilələrimizdəki qorumalara — GDPR tətbiq olunduqda Aİ Standart Müqavilə Müddəalarına, digər hallarda bərabər müqavilə qorumalarına — əsaslanırıq."
        ]
      },
      {
        "heading": "10. Məlumatları nə qədər saxlayırıq",
        "paragraphs": [
          "| Məlumat | Saxlama müddəti | |---|---| | Hesab, profil, CV məlumatları | hesabınız mövcud olduğu müddətdə; hesab silindikdən sonra 30 gün ərzində silinir | | İşəgötürənlərə çatdırılmış müraciətlər | sizin nüsxəniz hesabınızla birlikdə silinir; İşəgötürənin nüsxəsi İşəgötürənin öhdəlikləri ilə tənzimlənir (6-cı bölmə) | | Mesajlar | hesabınız mövcud olduğu müddətdə; silinmə zamanı kimliyiniz söhbətlərdən çıxarılır | | Ödəniş/əməliyyat qeydləri | vergi və mühasibat qanunvericiliyinin tələb etdiyi müddətdə (adətən 5 il) | | Texniki qeydlər | 12 ayadək | | Ehtiyat nüsxələr | silinmə yayıldıqdan sonra 30 gün ərzində köhnəlir |"
        ]
      },
      {
        "heading": "11. Hüquqlarınız",
        "paragraphs": [
          "Hüquqlarınız: məlumatlarınıza giriş və surət almaq; qeyri-dəqiq məlumatları düzəltmək; məlumatlarınızı silmək; qanuni maraqlara əsaslanan emalı məhdudlaşdırmaq və ya ona etiraz etmək; razılığı istənilən vaxt geri götürmək (əvvəlki emala təsir etmədən); təqdim etdiyiniz məlumatların daşınabilirliyi (maşınla oxuna bilən ixrac).",
          "Hüquqlarınızı həyata keçirmək üçün tətbiqdəki alətlərdən istifadə edin və ya info@axtaris.app ünvanına yazın. 30 gün ərzində cavab veririk. Aİ/AİZ və ya Birləşmiş Krallıqdasınızsa, yerli nəzarət orqanına da şikayət edə bilərsiniz; Azərbaycanda — fərdi məlumatların qorunmasına nəzarət edən səlahiyyətli orqana."
        ]
      },
      {
        "heading": "12. Hesabınızın silinməsi",
        "paragraphs": [
          "• Tətbiqdə: Profil → Parametrlər → Hesabı sil. Bu, hesabınızı və 10-cu bölmədə göstərilən məlumatları həmişəlik silir.",
          "• Vebdə: https://axtaris.app/legal/delete-account — tətbiqi yenidən quraşdırmadan silinmə üçün.",
          "Silinmə geri dönməzdir; silinmiş hesabı bərpa edə bilmərik."
        ]
      },
      {
        "heading": "13. Razılıq bəyanatı (Azərbaycan Respublikasının Qanunu № 998-IIIQ)",
        "paragraphs": [
          "Qeydiyyatdan keçməklə fərdi məlumatlarınızın [AXTARIS MMC — qeydiyyat gözlənilir; VÖEN: __________] (operator) tərəfindən 2-ci bölmədəki məqsədlərlə (iş axtarışı platforması Xidmətinin göstərilməsi və sadalanan əlaqəli məqsədlər) emalına razılıq verirsiniz. Razılıq hesabınız mövcud olduğu müddətdə qüvvədədir; onu istənilən vaxt hesabınızı silməklə (12-ci bölmə) və ya info@axtaris.app ünvanına yazmaqla geri götürə bilərsiniz — bundan sonra məlumatlarınız 10-cu bölmədə təsvir olunduğu kimi silinir və ya arxivləşdirilir. İstəyə bağlı qeyd olunmuş məlumatların verilməsi könüllüdür; əsas hesab məlumatları Xidmətin göstərilməsi üçün zəruridir."
        ]
      },
      {
        "heading": "14. Cookie-lər (veb sayt)",
        "paragraphs": [
          "axtaris.app saytı həmişə yalnız ciddi zəruri cookie-lərdən/yaddaşdan istifadə edir (məsələn, dil seçimi, cookie bannerindəki seçiminiz).",
          "Həmçinin sayta ümumi baxışı qiymətləndirmək üçün (baxılan səhifələr, gözləmə siyahısına qeydiyyatlar) Google Analytics 4-dən istifadə edirik. Analitika cookie-ləri (_ga, _ga_*, 14 ayadək qüvvədədir) yalnız ilk ziyarətinizdə göstərilən banneri qəbul etdiyiniz halda qoyulur; qəbul etməzdən əvvəl Google Consent Mode analitika yaddaşını rədd edilmiş vəziyyətdə saxlayır. Razılığınızı istənilən vaxt brauzerinizdə axtaris.app sayt məlumatlarını təmizləməklə geri götürə bilərsiniz — banner yenidən görünəcək. Reklam və saytlararası izləmə cookie-ləri işlətmirik və Google bu inteqrasiya vasitəsilə adınızı və ya e-poçtunuzu almır."
        ]
      },
      {
        "heading": "15. Uşaqlar",
        "paragraphs": [
          "Xidmət 16 yaş və yuxarı istifadəçilər üçündür. 16 yaşdan kiçik uşaqların məlumatlarını bilərəkdən emal etmirik; uşağın Xidmətdən istifadə etdiyini düşünürsünüzsə, info@axtaris.app ünvanına bildirin — hesabı siləcəyik."
        ]
      },
      {
        "heading": "16. Təhlükəsizlik",
        "paragraphs": [
          "Məlumatları ötürülmə zamanı şifrələmə, verilənlər bazasında girişə nəzarət və sətir səviyyəli təhlükəsizlik (RLS), sirlərin idarə edilməsi və əməkdaş girişində minimal səlahiyyət prinsipi ilə qoruyuruq. Heç bir sistem tam təhlükəsiz deyil; pozuntu məlumatlarınıza təsir edərsə, qanunun tələb etdiyi kimi sizi və səlahiyyətli orqanları məlumatlandıracağıq (tətbiq olunduqda GDPR üzrə orqana 72 saatlıq bildiriş daxil olmaqla)."
        ]
      },
      {
        "heading": "17. Push bildirişlər",
        "paragraphs": [
          "Push bildirişlər (yeni mesajlar, müraciət yenilikləri, uyğunluqlar) istəyə bağlıdır — tətbiq icazə soruşur və icazəni istənilən vaxt cihaz parametrlərində ləğv edə bilərsiniz. Onları çatdırmaq üçün push tokeninizi saxlayırıq; hesabdan çıxdıqda və ya hesab silindikdə token silinir."
        ]
      },
      {
        "heading": "18. Siyasətdə dəyişikliklər",
        "paragraphs": [
          "Bu Siyasəti yeniləyə bilərik. Əhəmiyyətli dəyişikliklər qüvvəyə minməzdən ən azı 15 gün əvvəl tətbiqdə və ya e-poçtla elan olunur. Cari versiya həmişə tətbiqdə (Hüquqi sənədlər) və axtaris.app saytında mövcuddur.",
          "Əlaqə",
          "AxtarIS — [AXTARIS MMC — qeydiyyat gözlənilir; VÖEN: __________] [QEYDİYYAT ÜNVANI] E-poçt: info@axtaris.app",
          "Əlaqəli sənədlər: İstifadə Şərtləri, İşəgötürən Şərtləri, İcma Qaydaları, Abunəlik və Geri Ödəniş Şərtləri."
        ]
      }
    ]
  },
  "ru": {
    "terms": [
      {
        "paragraphs": [
          "Дата вступления в силу: [ДАТА ВСТУПЛЕНИЯ В СИЛУ]",
          "Настоящие Условия использования («Условия») — юридически обязательное соглашение между вами и [AXTARIS MMC — регистрация ожидается; VÖEN: __________], компанией, зарегистрированной в Азербайджанской Республике по адресу [ЮРИДИЧЕСКИЙ АДРЕС] («AxtarIS», «мы»). Они регулируют использование мобильных приложений AxtarIS, сайта axtaris.app и связанных сервисов (вместе — «Сервис»).",
          "Создавая аккаунт или используя Сервис, вы принимаете эти Условия. Если вы не согласны — не используйте Сервис.",
          "Если вы используете Сервис от имени компании как работодатель, к вам также применяются Условия для работодателей, имеющие приоритет при противоречии."
        ]
      },
      {
        "heading": "1. Термины",
        "paragraphs": [
          "• «Кандидат» — физическое лицо, использующее Сервис для поиска работы, создания профессионального профиля или отклика на Вакансии.",
          "• «Работодатель» — юридическое лицо или предприниматель, использующие Сервис для публикации Вакансий, поиска Кандидатов и связи с ними.",
          "• «Вакансия» — объявление о работе, опубликованное Работодателем в Сервисе.",
          "• «Пользовательский контент» — любой контент, который вы размещаете в Сервисе: данные профиля, резюме (CV), отклики, сообщения, изображения, описания компаний, Вакансии и подобные материалы.",
          "• «Подписка» — платный план, открывающий дополнительные функции, описанный в Условиях подписки и возврата средств."
        ]
      },
      {
        "heading": "2. Кто может пользоваться Сервисом",
        "paragraphs": [
          "Вам должно быть не менее 16 лет. Используя Сервис, вы подтверждаете, что вам 16 или больше, а если вы действуете от имени Работодателя — что у вас есть полномочия его представлять."
        ]
      },
      {
        "heading": "3. Ваш аккаунт",
        "paragraphs": [
          "3.1. При регистрации указывайте точные, актуальные данные и поддерживайте их в актуальном состоянии. Профили и резюме должны описывать вас правдиво.",
          "3.2. Вы отвечаете за конфиденциальность своих учётных данных и за все действия в вашем аккаунте. При подозрении на несанкционированный доступ немедленно напишите на info@axtaris.app.",
          "3.3. Один человек — один аккаунт. Запрещено создавать аккаунты за других, выдавать себя за другое лицо или указывать ложные данные о личности."
        ]
      },
      {
        "heading": "4. Что такое AxtarIS — и чем он не является",
        "paragraphs": [
          "4.1. AxtarIS — это платформа, соединяющая Кандидатов и Работодателей: она размещает Вакансии, профессиональные профили, отклики и переписку сторон.",
          "4.2. AxtarIS не является работодателем, агентством занятости или рекрутером. Мы не нанимаем Кандидатов, не являемся стороной какого-либо трудового договора, собеседования, оффера или трудовых отношений между Кандидатом и Работодателем и не действуем как чей-либо агент.",
          "4.3. Мы не гарантируем Кандидатам собеседования, офферы или трудоустройство, а Работодателям — подходящих кандидатов. Оценки соответствия и рекомендации — информационные инструменты, а не обещания.",
          "4.4. Работодатели — независимые стороны. Мы не проверяем каждое утверждение в Вакансиях и профилях. Будьте благоразумны: никогда не платите за трудоустройство и сообщайте о подозрительном поведении (раздел 7)."
        ]
      },
      {
        "heading": "5. Лицензия на приложение",
        "paragraphs": [
          "5.1. Мы предоставляем вам личную, неисключительную, непередаваемую, отзывную лицензию на установку приложений AxtarIS и доступ к Сервису в целях, описанных в Условиях.",
          "5.2. В Google Play и в вебе этот раздел выполняет роль лицензионного соглашения с конечным пользователем. В App Store к загрузке приложения применяется стандартное лицензионное соглашение Apple (Licensed Application EULA); Сервис регулируется настоящими Условиями.",
          "5.3. Запрещается копировать, изменять, распространять, продавать, декомпилировать Сервис, автоматически собирать из него данные (scraping), а также использовать его для создания конкурирующей базы вакансий или профилей — кроме случаев, разрешённых императивными нормами закона."
        ]
      },
      {
        "heading": "6. Пользовательский контент",
        "paragraphs": [
          "6.1. Права на ваш контент остаются у вас.",
          "6.2. Вы предоставляете AxtarIS неисключительную, действующую по всему миру, безвозмездную лицензию размещать, хранить, воспроизводить, адаптировать (для форматирования), показывать и передавать ваш контент исключительно для работы, предоставления, защиты и улучшения Сервиса — например, чтобы показать ваш профиль Работодателю, которому вы откликнулись, доставить ваши сообщения или сформировать предпросмотр резюме. Лицензия прекращается при удалении контента из Сервиса, кроме резервных копий, хранимых ограниченное время, и контента, уже правомерно доставленного другим пользователям (например, отклик, который Работодатель уже получил).",
          "6.3. Вы отвечаете за свой контент. Не размещайте то, на что у вас нет прав, и не включайте чужие персональные данные без разрешения.",
          "6.4. Важно для резюме и профилей: не указывайте чувствительные персональные данные (здоровье, религия, политические взгляды и т.п.) — Сервис их не запрашивает и в них не нуждается. См. Политику конфиденциальности."
        ]
      },
      {
        "heading": "7. Допустимое использование и модерация",
        "paragraphs": [
          "7.1. Правила сообщества — часть настоящих Условий; они определяют, что запрещено: в том числе фейковые вакансии, требование оплаты с кандидатов, мошенничество с предоплатой, пирамиды/MLM, дискриминационные требования, преследование и незаконный контент.",
          "7.2. Как работает модерация. Мы используем жалобы пользователей, встроенные инструменты жалоб и блокировки и внутреннюю проверку нашей командой. Получив уведомление о контенте, нарушающем Условия или закон, либо обнаружив его сами, мы можем удалить или ограничить контент, вынести предупреждение, ограничить функции, приостановить или удалить аккаунт — соразмерно нарушению. Где это практически возможно, мы сообщаем, какой контент затронут и почему, и как возразить (пишите на info@axtaris.app). Жалобы рассматриваются в сроки, указанные в Правилах сообщества.",
          "7.3. Мы можем сохранять и раскрывать контент, когда этого требует закон или законное требование компетентного органа."
        ]
      },
      {
        "heading": "8. Подписки и платежи",
        "paragraphs": [
          "8.1. Часть Сервиса бесплатна. Платные Подписки открывают дополнительные функции для Кандидатов и Работодателей.",
          "8.2. Цены, периоды, продление, отмена и возвраты описаны в Условиях подписки и возврата средств, являющихся частью настоящих Условий. Кратко: подписки продлеваются автоматически до отмены; покупки через Apple и Google управляются и возвращаются через них; покупки на нашем сайте обрабатывает Paddle как официальный продавец (merchant of record)."
        ]
      },
      {
        "heading": "9. Сторонние сервисы",
        "paragraphs": [
          "Сервис опирается на сторонних провайдеров (хостинг, push-уведомления, обработка платежей, ИИ-функции для текста). Их роль в обработке ваших данных описана в Политике конфиденциальности. Мы не отвечаем за сторонние сайты и сервисы, на которые ведут ссылки из Вакансий и сообщений."
        ]
      },
      {
        "heading": "10. Интеллектуальная собственность",
        "paragraphs": [
          "Сервис — включая программное обеспечение, дизайн, логотипы и базы данных, но исключая Пользовательский контент — принадлежит AxtarIS или его лицензиарам. Условия не передают вам никаких прав на него. Название «AxtarIS» и связанные знаки нельзя использовать без нашего письменного согласия."
        ]
      },
      {
        "heading": "11. Доступность и изменения Сервиса",
        "paragraphs": [
          "Мы стараемся поддерживать доступность и безопасность Сервиса, но не обещаем бесперебойную и безошибочную работу. Мы можем изменять, добавлять и прекращать функции. О существенном прекращении Сервиса мы заранее уведомим через приложение или по почте."
        ]
      },
      {
        "heading": "12. Отказ от гарантий",
        "paragraphs": [
          "В пределах, допустимых законом, Сервис предоставляется «как есть» и «как доступно». Мы не гарантируем точность Вакансий, профилей, оценок соответствия и предложений ИИ."
        ]
      },
      {
        "heading": "13. Ответственность",
        "paragraphs": [
          "13.1. В пределах, допустимых законом, AxtarIS не отвечает за: косвенные убытки; упущенную выгоду, возможности или данные; поведение Кандидатов и Работодателей (включая решения о найме, трудовые споры и публикуемый ими контент); события вне нашего разумного контроля.",
          "13.2. В пределах, допустимых законом, наша совокупная ответственность за любой 12-месячный период ограничена большей из сумм: (a) уплаченного вами нам за этот период и (b) 100 AZN.",
          "13.3. Ничто в Условиях не исключает ответственность, которую нельзя исключить по закону, включая ответственность за умысел или грубую неосторожность, а также за вред жизни и здоровью, причинённый по неосторожности."
        ]
      },
      {
        "heading": "14. Ваши права потребителя",
        "paragraphs": [
          "Ничто в настоящих Условиях не ограничивает императивные права потребителей страны вашего проживания. Если вы используете Сервис как потребитель в ЕС, Великобритании или иной юрисдикции с обязательной защитой потребителей, за вами сохраняются её гарантии, и вы вправе обращаться в местные суды там, где закон даёт такое право."
        ]
      },
      {
        "heading": "15. Прекращение",
        "paragraphs": [
          "15.1. Вы можете в любой момент прекратить использование и удалить аккаунт — в приложении (Профиль → Настройки → Удалить аккаунт) или через веб-страницу удаления, указанную в Политике конфиденциальности.",
          "15.2. Мы можем приостановить или удалить ваш аккаунт за существенное или повторное нарушение Условий, по юридическим причинам или для защиты Сервиса и его пользователей — в порядке модерации из раздела 7. Где это соразмерно, сначала предупреждаем.",
          "15.3. Перед удалением аккаунта вы можете выгрузить свои данные (резюме и данные профиля) средствами приложения или запросить копию на info@axtaris.app. Судьба данных после удаления описана в Политике конфиденциальности."
        ]
      },
      {
        "heading": "16. Изменения Условий",
        "paragraphs": [
          "Мы можем обновлять Условия. О существенных изменениях сообщим минимум за 15 дней в приложении или по почте. Если вы не согласны — прекратите использование и удалите аккаунт до вступления изменений в силу; продолжение использования означает согласие."
        ]
      },
      {
        "heading": "17. Применимое право и споры",
        "paragraphs": [
          "17.1. Условия регулируются законодательством Азербайджанской Республики.",
          "17.2. Споры разрешаются компетентными судами города Баку — с учётом раздела 14: потребители с императивными правами на местную подсудность сохраняют их.",
          "17.3. Прежде чем идти в суд, напишите на info@axtaris.app — большинство вопросов решается напрямую."
        ]
      },
      {
        "heading": "18. Заключительные положения",
        "paragraphs": [
          "Недействительность отдельного положения не затрагивает остальные. Настоящие Условия, Условия для работодателей (для Работодателей), Политика конфиденциальности, Правила сообщества и Условия подписки и возврата средств составляют полное соглашение между вами и AxtarIS о Сервисе. Мы можем уступить это соглашение в рамках слияния или продажи бизнеса; вы уступать его не можете. Неприменение нами какого-либо положения не означает отказ от него.",
          "Контакты",
          "AxtarIS — [AXTARIS MMC — регистрация ожидается; VÖEN: __________] [ЮРИДИЧЕСКИЙ АДРЕС] Email: info@axtaris.app",
          "Связанные документы: Условия для работодателей, Политика конфиденциальности, Правила сообщества, Условия подписки и возврата средств."
        ]
      }
    ],
    "privacy": [
      {
        "paragraphs": [
          "Дата вступления в силу: [ДАТА ВСТУПЛЕНИЯ В СИЛУ]",
          "Настоящая Политика объясняет, как [AXTARIS MMC — регистрация ожидается; VÖEN: __________], [ЮРИДИЧЕСКИЙ АДРЕС] («AxtarIS», «мы») обрабатывает персональные данные при использовании мобильных приложений AxtarIS, сайта axtaris.app и связанных сервисов («Сервис»).",
          "AxtarIS является оператором (контролёром) описанных здесь персональных данных, если не указано иное (см. раздел 6 о Работодателях). Контакт: info@axtaris.app.",
          "Политика составлена с учётом Закона Азербайджанской Республики «О персональных данных» (№ 998-IIIQ) и — поскольку Сервис доступен также пользователям в ЕС и других странах — Общего регламента ЕС по защите данных («GDPR») как общего высокого стандарта."
        ]
      },
      {
        "heading": "1. Какие данные мы собираем",
        "paragraphs": [
          "Данные аккаунта — имя, email, пароль (хранится в виде хеша), телефон (по желанию), роль аккаунта (кандидат/работодатель), язык.",
          "Профиль кандидата и резюме — опыт работы, образование, навыки, языки, сертификаты, ожидаемая зарплата, город, доступность, фото профиля, загруженные файлы резюме и данные, извлечённые из них (см. раздел 8 об ИИ-функциях).",
          "Данные работодателя — название компании, описание, логотип, регистрационные данные, контактные лица, опубликованные вакансии.",
          "Отклики и взаимодействия — вакансии, на которые вы откликнулись, ответы на отборочные вопросы, сопроводительные письма, сохранённые вакансии и поиски, приглашения, просмотры профиля.",
          "Сообщения — содержание переписки кандидатов и работодателей на платформе, включая изображения, а также переписка с поддержкой.",
          "Платёжные данные — ваш план подписки, её статус и ссылки на транзакции. Мы никогда не видим и не храним полные номера карт: платежи обрабатывают Apple, Google или Paddle (раздел 7).",
          "Технические данные — тип устройства, ОС, версия приложения, язык, push-токен, IP-адрес и журналы событий (вход, ошибки), необходимые для работы и защиты Сервиса.",
          "Аналитика использования — события в приложении (просмотры экранов, отправленные отклики), используемые в агрегированном виде для улучшения Сервиса.",
          "Мы сознательно не собираем специальные категории данных (здоровье, религия, политические взгляды, биометрия и т.п.). Не указывайте их в резюме, профиле и сообщениях — Сервис их не запрашивает и в них не нуждается."
        ]
      },
      {
        "heading": "2. Зачем мы обрабатываем данные (цели и правовые основания)",
        "paragraphs": [
          "| Цель | Примеры | Основание (GDPR) | |---|---|---| | Предоставление Сервиса | аккаунты, профили, публикация вакансий, доставка откликов и сообщений, подбор | Договор (ст. 6(1)(b)) | | Платежи и подписки | статус плана, права доступа, квитанции | Договор; правовая обязанность (бухучёт) | | Безопасность и модерация | обработка жалоб, блокировки, борьба с мошенничеством и фейковыми вакансиями | Законные интересы (ст. 6(1)(f)) — безопасность платформы | | Коммуникации | сервисные письма, push-уведомления об откликах, сообщениях, совпадениях | Договор; согласие для необязательных уведомлений (push управляется в настройках устройства) | | ИИ-функции | разбор резюме, текстовые подсказки по вашему запросу | Договор — вызванная вами функция | | Улучшение и статистика | агрегированная аналитика, отладка | Законные интересы (ст. 6(1)(f)) | | Соблюдение закона | ответы на законные запросы, налоговые/бухгалтерские записи | Правовая обязанность (ст. 6(1)(c)) |",
          "По Закону АР «О персональных данных» главное основание обработки — ваше согласие, данное при регистрации (раздел 13), наряду с обработкой, необходимой для исполнения договора с нами."
        ]
      },
      {
        "heading": "3. Где хранятся данные",
        "paragraphs": [
          "База данных и файловое хранилище Сервиса размещены у Supabase в регионе [РЕГИОН SUPABASE — уточнить в панели]. Если этот регион вне вашей страны, применяется раздел 9 (международные передачи)."
        ]
      },
      {
        "heading": "4. Кто видит ваши данные внутри Сервиса",
        "paragraphs": [
          "• Профиль кандидата виден Работодателям в поиске талантов в соответствии с вашими настройками и функциями плана; ваши отклики (профиль, резюме, ответы, письмо) видны Работодателю, на чью вакансию вы откликнулись.",
          "• Вакансии и профили компаний публичны для пользователей Сервиса.",
          "• Сообщения видны участникам переписки, а в тредах поддержки — также нашим сотрудникам поддержки."
        ]
      },
      {
        "heading": "5. Кто обрабатывает данные для нас (процессоры)",
        "paragraphs": [
          "Мы используем ограниченный набор провайдеров, связанных соглашениями об обработке данных:",
          "| Провайдер | Роль | Данные | |---|---|---| | Supabase (хостинг-инфраструктура) | база данных, аутентификация, файлы, серверные функции | все данные Сервиса | | Expo (доставка push) | доставка push-уведомлений на устройство | push-токен, содержание уведомления | | Paddle | обработка платежей на сайте (официальный продавец — merchant of record, раздел 7) | данные покупки и биллинга | | Apple / Google | встроенные покупки, дистрибуция приложений | данные покупок по их политикам | | OpenAI (через наш защищённый прокси) | ИИ-функции для текста (раздел 8) | текст, который вы отправляете этим функциям | | Google Analytics | аналитика использования сайта (раздел 14), только после согласия в баннере cookie | псевдонимизированные данные использования (просмотренные страницы, тип устройства/браузера) |",
          "Мы не продаём персональные данные и не передаём их рекламодателям."
        ]
      },
      {
        "heading": "6. Работодатели — независимые операторы",
        "paragraphs": [
          "Когда вы откликаетесь на вакансию или принимаете приглашение, Работодатель получает данные вашего отклика (профиль, резюме, ответы, адресованные ему сообщения). С этого момента Работодатель обрабатывает эти данные как независимый оператор для собственного найма и по собственным правовым обязанностям. Наши Условия для работодателей обязывают их использовать ваши данные только для найма на конкретную роль, защищать их и удалять по завершении найма или по вашему требованию. О практике конкретного Работодателя обращайтесь к нему; мы поможем, чем сможем (info@axtaris.app)."
        ]
      },
      {
        "heading": "7. Платежи",
        "paragraphs": [
          "• В приложениях подписки покупаются через Apple In-App Purchase или Google Play Billing. Платёж обрабатывают Apple/Google; мы получаем подтверждение покупки и статус подписки, но не данные карты.",
          "• На сайте покупки обрабатывает Paddle как официальный продавец — Paddle является продавцом по транзакции, обрабатывает платёжные данные по своей политике конфиденциальности и передаёт нам статус подписки."
        ]
      },
      {
        "heading": "8. ИИ-функции",
        "paragraphs": [
          "Некоторые функции используют языковые модели ИИ (OpenAI, через контролируемый нами прокси): разбор загруженного резюме в поля профиля, составление и улучшение текстов профиля и сопроводительных писем, составление описаний вакансий, переводы. Отправленный этим функциям текст обрабатывается для предоставления запрошенной функции и не используется ни нами, ни — по условиям нашего провайдера — провайдером ИИ для обучения моделей. Не отправляйте ИИ-функциям чужие персональные и чувствительные данные. Результаты ИИ могут быть неточными; проверяйте их перед использованием."
        ]
      },
      {
        "heading": "9. Международные передачи",
        "paragraphs": [
          "При передаче данных за пределы вашей юрисдикции (например, хостинг- или ИИ-провайдерам) мы опираемся на гарантии в соглашениях с ними, включая Стандартные договорные положения ЕС, где применим GDPR, и эквивалентные договорные гарантии в иных случаях."
        ]
      },
      {
        "heading": "10. Сроки хранения",
        "paragraphs": [
          "| Данные | Срок | |---|---| | Аккаунт, профиль, резюме | пока существует аккаунт; удаляются в течение 30 дней после удаления аккаунта | | Отклики, доставленные Работодателям | ваша копия удаляется с аккаунтом; копия Работодателя регулируется его обязанностями (раздел 6) | | Сообщения | пока существует аккаунт; при удалении ваша личность удаляется из переписок | | Платёжные записи | в течение сроков налогового и бухгалтерского законодательства (обычно 5 лет) | | Технические журналы | до 12 месяцев | | Резервные копии | устаревают в течение 30 дней после распространения удаления |"
        ]
      },
      {
        "heading": "11. Ваши права",
        "paragraphs": [
          "Вы вправе: получить доступ к данным и их копию; исправить неточные данные; удалить данные; ограничить обработку или возразить против обработки на основании законных интересов; отозвать согласие в любой момент (не затрагивая предыдущую обработку); получить данные в переносимом виде (портируемость).",
          "Используйте инструменты в приложении или пишите на info@axtaris.app. Отвечаем в течение 30 дней. В ЕС/ЕЭЗ и Великобритании вы также можете подать жалобу в местный надзорный орган; в Азербайджане — в уполномоченный орган по защите персональных данных."
        ]
      },
      {
        "heading": "12. Удаление аккаунта",
        "paragraphs": [
          "• В приложении: Профиль → Настройки → Удалить аккаунт. Аккаунт и данные из раздела 10 удаляются безвозвратно.",
          "• В вебе: https://axtaris.app/legal/delete-account — удаление без переустановки приложения.",
          "Удаление необратимо; восстановить удалённый аккаунт невозможно."
        ]
      },
      {
        "heading": "13. Заявление о согласии (Закон АР № 998-IIIQ)",
        "paragraphs": [
          "Регистрируясь, вы даёте согласие на обработку ваших персональных данных оператором [AXTARIS MMC — регистрация ожидается; VÖEN: __________] в целях раздела 2 (предоставление Сервиса платформы поиска работы и перечисленные связанные цели). Согласие действует, пока существует ваш аккаунт; вы можете отозвать его в любой момент, удалив аккаунт (раздел 12) или написав на info@axtaris.app, после чего данные удаляются или архивируются согласно разделу 10. Предоставление данных, помеченных как необязательные, добровольно; базовые данные аккаунта необходимы для предоставления Сервиса."
        ]
      },
      {
        "heading": "14. Cookie (сайт)",
        "paragraphs": [
          "Сайт axtaris.app всегда использует строго необходимые cookie/хранилище (например, выбор языка, ваш выбор в баннере cookie).",
          "Мы также используем Google Analytics 4 для оценки общей посещаемости сайта (просмотры страниц, регистрации в лист ожидания). Аналитические cookie (_ga, _ga_*, срок действия до 14 месяцев) устанавливаются только если вы согласитесь в баннере, показанном при первом посещении; до согласия Google Consent Mode держит аналитическое хранилище отклонённым. Вы можете отозвать согласие в любой момент, очистив данные сайта axtaris.app в браузере — баннер появится снова. Рекламных и кросс-сайтовых трекинговых cookie нет, и Google не получает через эту интеграцию ваше имя или email."
        ]
      },
      {
        "heading": "15. Дети",
        "paragraphs": [
          "Сервис предназначен для пользователей от 16 лет. Мы сознательно не обрабатываем данные детей младше 16; если вы считаете, что ребёнок пользуется Сервисом, сообщите на info@axtaris.app — аккаунт будет удалён."
        ]
      },
      {
        "heading": "16. Безопасность",
        "paragraphs": [
          "Мы защищаем данные шифрованием при передаче, контролем доступа и построчной защитой (RLS) в базе данных, управлением секретами и принципом минимальных привилегий для персонала. Абсолютно защищённых систем не существует; при инциденте, затрагивающем ваши данные, мы уведомим вас и компетентные органы, как требует закон (включая 72-часовое уведомление органа по GDPR, где применимо)."
        ]
      },
      {
        "heading": "17. Push-уведомления",
        "paragraphs": [
          "Push-уведомления (новые сообщения, статусы откликов, совпадения) необязательны — приложение запрашивает разрешение, и его можно отозвать в настройках устройства. Мы храним push-токен для доставки и удаляем его при выходе из аккаунта или удалении аккаунта."
        ]
      },
      {
        "heading": "18. Изменения Политики",
        "paragraphs": [
          "Мы можем обновлять Политику. О существенных изменениях сообщим минимум за 15 дней в приложении или по почте. Актуальная версия всегда доступна в приложении (Юридические документы) и на axtaris.app.",
          "Контакты",
          "AxtarIS — [AXTARIS MMC — регистрация ожидается; VÖEN: __________] [ЮРИДИЧЕСКИЙ АДРЕС] Email: info@axtaris.app",
          "Связанные документы: Условия использования, Условия для работодателей, Правила сообщества, Условия подписки и возврата средств."
        ]
      }
    ]
  }
};
